#include "PresetLibraryChoices.h"

namespace UI::PresetLibraryChoices
{
juce::StringArray categoryChoices()
{
    return {
        "User",
        "Bass",
        "Stab",
        "Lead",
        "House",
        "House/Acid",
        "House/Bass",
        "House/Chords",
        "House/Keys",
        "House/Plucks",
        "House/Indie Dance",
        "House/Italo Disco",
        "House/Nu Disco",
        "House/Balearic",
        "House/Afro Melodic",
        "House/Progressive",
        "House/Hard House",
        "House/Lo-Fi",
        "Afro House",
        "Amapiano",
        "Organic House",
        "Melodic Techno",
        "Drum & Bass",
        "Bass House",
        "Hard Techno",
        "Indie Dance",
        "Trance",
        "Ambient",
        "Future Garage",
        "Latin Tech",
        "Tech House",
        "Tech House/Bass",
        "Tech House/Deep Tech",
        "Tech House/Afro Tech",
        "Techno",
        "Techno/Dub",
        "Techno/Hardgroove",
        "Techno/Peak Time",
        "Techno/Detroit",
        "Techno/Melodic",
        "Techno/Stabs",
        "Minimal",
        "Minimal/FM",
        "Minimal/Deep",
        "Minimal/Plucks",
        "Romanian Minimal",
        "UKG",
        "UKG/Bass",
        "UKG/Chops",
        "UKG/Organ",
        "UKG/Stabs",
        "UKG/Bells",
        "Electro Breaks",
        "FX",
        "Sequence",
        "Sample"
    };
}

juce::StringArray filterChoices()
{
    return {
        "All",
        "Favorites",
        "Recent",
        "Rated",
        "5 Stars",
        "4+ Stars",
        "Macro Rich",
        "Generated",
        "User",
        "Factory",
        "Similar",
        "Five Star Crate",
        "Club Bass",
        "Chord Stabs",
        "Dub Stabs",
        "Bass",
        "Chord",
        "Pad",
        "Stab",
        "Lead",
        "House",
        "Tech House",
        "Techno",
        "Minimal",
        "UKG",
        "Afro House",
        "Organic House",
        "Drum & Bass",
        "Hard Techno",
        "Trance",
        "Ambient",
        "Latin Tech",
        "Bass House",
        "Amapiano",
        "Hardgroove",
        "Future Garage",
        "Speed Garage",
        "Deep Tech",
        "Indie Dance",
        "Italo Disco",
        "Balearic House",
        "Acid House",
        "Nu Disco",
        "Afro Tech",
        "Afro Melodic",
        "Progressive House",
        "Hard House",
        "Peak Time Techno",
        "Detroit Techno",
        "Melodic Techno",
        "Minimal FM",
        "Deep Minimal",
        "Lo-Fi House",
        "French House",
        "Soulful House",
        "Garage House",
        "Microhouse",
        "Raw Techno",
        "Tribal Tech House",
        "Breaks House",
        "Chicago House",
        "Classic House",
        "Funky House",
        "Melodic House",
        "Romanian Minimal",
        "Dub Techno",
        "Electro Breaks",
        "FX",
        "Sequence",
        "Sample",
        "Project Pack",
        "Factory Pack",
        "UKG Essentials",
        "UKG Basslines",
        "Garage Chops",
        "House Chords",
        "House Tools",
        "House Expansion",
        "Afro House Rituals",
        "Amapiano Log Lab",
        "Melodic Techno Motion",
        "Organic Progressive",
        "Drum & Bass Tools",
        "Bass House Weapons",
        "Hard Techno Rave",
        "Indie Dance Dark Disco",
        "Trance Progressive",
        "Ambient Electronica",
        "Future Garage Dub",
        "Latin Tech Tribal",
        "Tech House Tools",
        "Tech House Expansion",
        "Minimal Plucks",
        "Minimal Tools",
        "Minimal Expansion",
        "Techno Stabs",
        "Techno Tools",
        "Techno Expansion",
        "UKG Expansion",
        "Dirty Tools",
        "Mono Safe",
        "Sequenced Grooves",
        "120-124 BPM",
        "125-128 BPM",
        "129-132 BPM",
        "133+ BPM"
    };
}

juce::StringArray sortChoices()
{
    return { "Name", "Rating", "Newest", "Category", "Pack", "BPM", "Key", "Author", "Source", "Macros" };
}

juce::StringArray packChoices()
{
    return {
        "User Pack",
        "Project Pack",
        "UKG Essentials",
        "UKG Basslines",
        "Garage Chops",
        "House Chords",
        "House Tools",
        "House Expansion",
        "Afro House Rituals",
        "Amapiano Log Lab",
        "Dub Stabs",
        "Tech House Tools",
        "Tech House Expansion",
        "Minimal Plucks",
        "Minimal Tools",
        "Minimal Expansion",
        "Dub Techno Tools",
        "Techno Tools",
        "Techno Expansion",
        "Melodic Techno Motion",
        "Organic Progressive",
        "Drum & Bass Tools",
        "Bass House Weapons",
        "Hard Techno Rave",
        "Indie Dance Dark Disco",
        "Trance Progressive",
        "Ambient Electronica",
        "Future Garage Dub",
        "Latin Tech Tribal",
        "UKG Expansion",
        "Electro Breaks Tools",
        "Factory Pack"
    };
}

juce::StringArray keyChoices()
{
    return {
        "Any Key",
        "C Min",
        "C# Min",
        "D Min",
        "D# Min",
        "E Min",
        "F Min",
        "F# Min",
        "G Min",
        "G# Min",
        "A Min",
        "A# Min",
        "B Min",
        "C Maj",
        "C# Maj",
        "D Maj",
        "D# Maj",
        "E Maj",
        "F Maj",
        "F# Maj",
        "G Maj",
        "G# Maj",
        "A Maj",
        "A# Maj",
        "B Maj"
    };
}

juce::StringArray bpmChoices()
{
    return { "Any Tempo", "120 BPM", "122 BPM", "124 BPM", "125 BPM", "126 BPM", "128 BPM", "130 BPM", "132 BPM", "134 BPM", "136 BPM", "138 BPM" };
}

juce::StringArray tagChoices()
{
    return {
        "All Tags",
        "Bass",
        "Chord",
        "Pluck",
        "Stab",
        "Sequenced",
        "Mono Safe",
        "Pump",
        "Wide",
        "FX",
        "Generated",
        "Random Lab",
        "Vocal Chop",
        "Sample",
        "Lead",
        "Organ",
        "House",
        "Tech House",
        "Techno",
        "Minimal",
        "UKG",
        "Bass House",
        "Amapiano",
        "Hardgroove",
        "Future Garage",
        "Speed Garage",
        "Deep Tech",
        "Indie Dance",
        "Italo Disco",
        "Balearic House",
        "Acid House",
        "Nu Disco",
        "Afro Tech",
        "Afro Melodic",
        "Progressive House",
        "Hard House",
        "Peak Time Techno",
        "Detroit Techno",
        "Melodic Techno",
        "Minimal FM",
        "Deep Minimal",
        "Lo-Fi House",
        "French House",
        "Soulful House",
        "Garage House",
        "Microhouse",
        "Raw Techno",
        "Tribal Tech House",
        "Breaks House",
        "Chicago House",
        "Classic House",
        "Funky House",
        "Melodic House",
        "Romanian Minimal",
        "Dub Techno",
        "Electro Breaks"
    };
}

int parseBpm(const juce::String& text)
{
    const auto bpm = text.retainCharacters("0123456789").getIntValue();
    return bpm >= 20 && bpm <= 300 ? bpm : 0;
}

juce::String formatBpm(int bpm)
{
    return bpm >= 20 && bpm <= 300 ? juce::String(bpm) + " BPM" : juce::String("Any Tempo");
}
}
