#!/usr/bin/env python3

from pathlib import Path
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "Resources" / "Factory Presets"


DEFAULTS = {
    "osc_wave": 1,
    "osc_octave": 0,
    "osc_tune": 0.0,
    "osc1_level": 1.0,
    "osc2_wave": 1,
    "osc2_octave": 0,
    "osc2_tune": 0.0,
    "osc2_level": 0.0,
    "sub_level": 0.0,
    "noise_level": 0.0,
    "amp_attack": 0.01,
    "amp_decay": 0.18,
    "amp_sustain": 0.65,
    "amp_release": 0.22,
    "filter_cutoff": 1800.0,
    "filter_resonance": 0.45,
    "filter_env_amount": 0.15,
    "filter_mode": 0,
    "drive_amount": 0.18,
    "output_gain": -8.0,
    "mono_mode": 0,
    "glide_time": 0.0,
    "unison_voices": 1,
    "unison_detune": 0.0,
    "unison_blend": 0.65,
    "unison_spread": 0.0,
    "macro_1": 0.0,
    "macro_2": 0.0,
    "macro_3": 0.0,
    "macro_4": 0.0,
    "lfo1_rate": 1.0,
    "lfo1_sync": 1,
    "lfo1_sync_rate": 1,
    "lfo1_shape": 0,
    "lfo1_depth": 0.45,
    "lfo1_phase": 0.0,
    "lfo1_retrigger": 1,
    "mod_env1_attack": 0.01,
    "mod_env1_decay": 0.22,
    "mod_env1_sustain": 0.0,
    "mod_env1_release": 0.12,
    "mod_env1_depth": 0.5,
    "random_amount": 0.45,
    "random_chaos": 0.25,
    "random_brightness_bias": 0.0,
    "random_drive_bias": 0.0,
    "random_motion_bias": 0.0,
    "random_recipe": 6,
    "random_lock_pitch": 0,
    "random_lock_envelope": 0,
    "random_lock_filter": 0,
    "random_lock_source": 0,
    "random_lock_sample": 0,
    "random_lock_fx": 0,
    "random_lock_output": 0,
    "random_lock_sequencer": 0,
    "sample_enabled": 0,
    "sample_start": 0.0,
    "sample_end": 1.0,
    "sample_reverse": 0,
    "sample_playback_mode": 1,
    "sample_transpose": 0.0,
    "sample_pitch_ramp": 0.0,
    "sample_gain": -6.0,
    "sample_mix": 0.75,
    "sample_stutter_enabled": 0,
    "sample_stutter_rate": 1,
    "sample_stutter_repeats": 3,
    "sequencer_enabled": 0,
    "sequencer_rate": 1,
    "sequencer_root": 36,
    "sequencer_gate": 0.55,
    "sequencer_swing": 0.0,
    "sequencer_groove_mode": 0,
    "sequencer_accent": 0.35,
    "sequencer_octave": 0,
    "sequencer_probability": 1.0,
    "sequencer_random_amount": 0.55,
    "fx_distortion_enabled": 0,
    "fx_distortion_amount": 0.2,
    "fx_bitcrush_enabled": 0,
    "fx_bitcrush_bits": 12.0,
    "fx_bitcrush_downsample": 1.0,
    "fx_bitcrush_mix": 0.25,
    "fx_pump_enabled": 0,
    "fx_pump_rate": 0,
    "fx_pump_depth": 0.35,
    "fx_pump_shape": 0.45,
    "fx_pump_phase": 0.0,
    "fx_tremolo_enabled": 0,
    "fx_tremolo_rate": 1,
    "fx_tremolo_depth": 0.28,
    "fx_tremolo_pan": 0.25,
    "fx_tremolo_shape": 0.45,
    "fx_tremolo_phase": 0.0,
    "fx_ring_enabled": 0,
    "fx_ring_frequency": 72.0,
    "fx_ring_depth": 0.35,
    "fx_ring_mix": 0.18,
    "fx_ring_bias": 0.45,
    "fx_chorus_enabled": 0,
    "fx_chorus_rate": 0.35,
    "fx_chorus_depth": 0.35,
    "fx_chorus_mix": 0.25,
    "fx_delay_enabled": 0,
    "fx_delay_time": 0.25,
    "fx_delay_feedback": 0.25,
    "fx_delay_mix": 0.2,
    "fx_reverb_enabled": 0,
    "fx_reverb_size": 0.35,
    "fx_reverb_damping": 0.45,
    "fx_reverb_mix": 0.2,
    "fx_width_enabled": 0,
    "fx_width_amount": 1.15,
    "fx_width_mono_cutoff": 120.0,
    "fx_tone_enabled": 0,
    "fx_tone_tilt": 0.0,
    "fx_tone_low_cut": 30.0,
    "fx_eq_enabled": 0,
    "fx_eq_low_gain": 0.0,
    "fx_eq_mid_gain": 0.0,
    "fx_eq_high_gain": 0.0,
    "fx_eq_trim": 0.0,
    "fx_phaser_enabled": 0,
    "fx_phaser_rate": 0.32,
    "fx_phaser_depth": 0.42,
    "fx_phaser_mix": 0.22,
    "fx_guard_enabled": 0,
    "fx_guard_push": 0.0,
    "fx_guard_ceiling": 0.92,
    "fx_flanger_enabled": 0,
    "fx_flanger_rate": 0.22,
    "fx_flanger_depth": 0.32,
    "fx_flanger_feedback": 0.18,
    "fx_flanger_mix": 0.18,
}

for slot_index in range(1, 9):
    DEFAULTS[f"mod_slot_{slot_index}_source"] = 0
    DEFAULTS[f"mod_slot_{slot_index}_destination"] = 0
    DEFAULTS[f"mod_slot_{slot_index}_amount"] = 0.0


def step(index, note, velocity, probability, timing=0.0):
    return {
        f"seq_step_{index}_enabled": "1",
        f"seq_step_{index}_note": str(note),
        f"seq_step_{index}_velocity": str(velocity),
        f"seq_step_{index}_probability": str(probability),
        f"seq_step_{index}_timing": str(timing),
    }


def blank_steps():
    props = {}
    for index in range(16):
        props[f"seq_step_{index}_enabled"] = "0"
        props[f"seq_step_{index}_note"] = "0"
        props[f"seq_step_{index}_velocity"] = "0.8"
        props[f"seq_step_{index}_probability"] = "1"
        props[f"seq_step_{index}_timing"] = "0"
    return props


def sequence(*steps):
    props = blank_steps()
    for item in steps:
        props.update(item)
    return props


PRESETS = [
    {
        "name": "UKG 2-Step Bass",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.86,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.12,
            "osc2_level": 0.32,
            "sub_level": 0.62,
            "amp_attack": 0.004,
            "amp_decay": 0.18,
            "amp_sustain": 0.38,
            "amp_release": 0.09,
            "filter_cutoff": 980.0,
            "filter_resonance": 0.38,
            "filter_env_amount": 0.32,
            "drive_amount": 0.22,
            "mono_mode": 1,
            "glide_time": 0.055,
            "macro_1": 0.18,
            "macro_2": 0.12,
            "macro_3": 0.24,
            "lfo1_depth": 0.2,
            "mod_env1_decay": 0.16,
            "mod_env1_depth": 0.34,
            "mod_slot_1_source": 1,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.08,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 3,
            "mod_slot_2_amount": 0.07,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 34.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.2,
            "fx_eq_mid_gain": -1.4,
            "fx_eq_high_gain": -0.4,
            "fx_eq_trim": -0.7,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 12.0,
            "fx_bitcrush_downsample": 2.0,
            "fx_bitcrush_mix": 0.08,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.28,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.02,
            "fx_width_mono_cutoff": 160.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.08,
            "fx_guard_ceiling": 0.91,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 38,
            "sequencer_gate": 0.34,
            "sequencer_swing": 0.42,
            "sequencer_groove_mode": 2,
            "sequencer_accent": 0.58,
            "sequencer_octave": -1,
            "sequencer_probability": 0.93,
            "sequencer_random_amount": 0.48,
            "random_recipe": 6,
        },
        "steps": sequence(
            step(0, 0, 0.88, 1.0),
            step(2, 7, 0.62, 0.85, 0.18),
            step(5, 3, 0.78, 0.95, 0.72),
            step(7, 10, 0.54, 0.72, 0.86),
            step(9, 0, 0.82, 1.0),
            step(11, -5, 0.66, 0.82, 0.78),
            step(14, 7, 0.76, 0.92, 0.26),
        ),
    },
    {
        "name": "UKG Shuffle Bass",
        "params": {
            "osc_wave": 2,
            "osc_octave": -1,
            "osc1_level": 0.82,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": 0.1,
            "osc2_level": 0.28,
            "sub_level": 0.58,
            "amp_attack": 0.004,
            "amp_decay": 0.16,
            "amp_sustain": 0.28,
            "amp_release": 0.08,
            "filter_cutoff": 760.0,
            "filter_resonance": 0.48,
            "filter_env_amount": 0.4,
            "drive_amount": 0.26,
            "mono_mode": 1,
            "glide_time": 0.075,
            "macro_3": 0.28,
            "lfo1_depth": 0.24,
            "mod_env1_decay": 0.14,
            "mod_env1_depth": 0.38,
            "mod_slot_1_source": 1,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.1,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 3,
            "mod_slot_2_amount": 0.09,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 32.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.0,
            "fx_eq_mid_gain": -1.8,
            "fx_eq_high_gain": -0.5,
            "fx_eq_trim": -0.8,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.34,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.0,
            "fx_width_mono_cutoff": 165.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.07,
            "fx_guard_ceiling": 0.9,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.3,
            "sequencer_swing": 0.5,
            "sequencer_groove_mode": 2,
            "sequencer_accent": 0.6,
            "sequencer_octave": -1,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.52,
            "random_recipe": 6,
        },
        "steps": sequence(
            step(0, 0, 0.9, 1.0),
            step(3, 7, 0.62, 0.76, 0.82),
            step(5, -5, 0.74, 0.9, 0.7),
            step(8, 0, 0.84, 1.0),
            step(10, 3, 0.56, 0.68, 0.24),
            step(13, -2, 0.78, 0.86, 0.76),
            step(15, 7, 0.52, 0.62, 0.88),
        ),
    },
    {
        "name": "UKG Dred Bass",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.88,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.09,
            "osc2_level": 0.42,
            "sub_level": 0.66,
            "amp_attack": 0.006,
            "amp_decay": 0.34,
            "amp_sustain": 0.32,
            "amp_release": 0.13,
            "filter_cutoff": 420.0,
            "filter_resonance": 0.58,
            "filter_env_amount": 0.5,
            "drive_amount": 0.32,
            "mono_mode": 1,
            "glide_time": 0.085,
            "unison_voices": 2,
            "unison_detune": 0.045,
            "unison_blend": 0.42,
            "unison_spread": 0.06,
            "macro_2": 0.2,
            "macro_3": 0.36,
            "lfo1_depth": 0.26,
            "mod_env1_attack": 0.09,
            "mod_env1_decay": 0.34,
            "mod_env1_sustain": 0.12,
            "mod_env1_release": 0.12,
            "mod_env1_depth": 0.52,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.24,
            "mod_slot_2_source": 1,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.08,
            "mod_slot_3_source": 2,
            "mod_slot_3_destination": 3,
            "mod_slot_3_amount": 0.13,
            "fx_tone_enabled": 1,
            "fx_tone_tilt": -0.14,
            "fx_tone_low_cut": 34.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.4,
            "fx_eq_mid_gain": -1.6,
            "fx_eq_high_gain": -0.8,
            "fx_eq_trim": -0.9,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 12.0,
            "fx_bitcrush_downsample": 2.5,
            "fx_bitcrush_mix": 0.09,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.32,
            "fx_pump_shape": 0.58,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.02,
            "fx_width_mono_cutoff": 170.0,
            "fx_phaser_enabled": 1,
            "fx_phaser_rate": 0.16,
            "fx_phaser_depth": 0.38,
            "fx_phaser_mix": 0.1,
            "fx_flanger_enabled": 1,
            "fx_flanger_rate": 0.11,
            "fx_flanger_depth": 0.24,
            "fx_flanger_feedback": 0.12,
            "fx_flanger_mix": 0.06,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.09,
            "fx_guard_ceiling": 0.9,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 37,
            "sequencer_gate": 0.32,
            "sequencer_swing": 0.48,
            "sequencer_groove_mode": 2,
            "sequencer_accent": 0.62,
            "sequencer_octave": -1,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.5,
            "random_recipe": 10,
        },
        "steps": sequence(
            step(0, 0, 0.9, 1.0),
            step(3, -5, 0.58, 0.72, 0.84),
            step(5, 7, 0.76, 0.92, 0.72),
            step(8, 0, 0.84, 1.0),
            step(11, 3, 0.62, 0.78, 0.8),
            step(13, -2, 0.74, 0.86, 0.68),
            step(15, 7, 0.52, 0.66, 0.92),
        ),
    },
    {
        "name": "UKG Organ Stab",
        "params": {
            "osc_wave": 2,
            "osc_octave": 0,
            "osc1_level": 0.78,
            "osc2_wave": 3,
            "osc2_octave": 0,
            "osc2_tune": 0.08,
            "osc2_level": 0.46,
            "sub_level": 0.08,
            "amp_attack": 0.003,
            "amp_decay": 0.18,
            "amp_sustain": 0.34,
            "amp_release": 0.1,
            "filter_cutoff": 2800.0,
            "filter_resonance": 0.3,
            "filter_env_amount": 0.2,
            "drive_amount": 0.12,
            "unison_voices": 2,
            "unison_detune": 0.04,
            "unison_spread": 0.34,
            "macro_1": 0.28,
            "macro_4": 0.18,
            "lfo1_depth": 0.18,
            "mod_env1_decay": 0.18,
            "mod_env1_depth": 0.42,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.15,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.06,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.025,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 110.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.6,
            "fx_eq_mid_gain": 0.3,
            "fx_eq_high_gain": 1.0,
            "fx_eq_trim": -0.5,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.16,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.12,
            "fx_tremolo_pan": 0.28,
            "fx_tremolo_shape": 0.48,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.26,
            "fx_chorus_enabled": 1,
            "fx_chorus_depth": 0.22,
            "fx_chorus_mix": 0.16,
            "fx_guard_enabled": 1,
            "fx_guard_ceiling": 0.94,
            "output_gain": -9.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.24,
            "sequencer_swing": 0.34,
            "sequencer_groove_mode": 1,
            "sequencer_accent": 0.56,
            "sequencer_probability": 0.92,
            "sequencer_random_amount": 0.38,
            "random_recipe": 7,
        },
        "steps": sequence(
            step(2, 0, 0.76, 1.0, 0.22),
            step(6, 3, 0.88, 0.95, 0.34),
            step(10, 7, 0.72, 0.88, 0.26),
            step(14, 10, 0.84, 0.86, 0.42),
        ),
    },
    {
        "name": "UKG Chord Stab",
        "params": {
            "osc_wave": 1,
            "osc_octave": 0,
            "osc1_level": 0.74,
            "osc2_wave": 1,
            "osc2_octave": 0,
            "osc2_tune": 7.0,
            "osc2_level": 0.58,
            "amp_attack": 0.003,
            "amp_decay": 0.14,
            "amp_sustain": 0.08,
            "amp_release": 0.14,
            "filter_cutoff": 4200.0,
            "filter_resonance": 0.34,
            "filter_env_amount": 0.24,
            "drive_amount": 0.18,
            "unison_voices": 3,
            "unison_detune": 0.08,
            "unison_spread": 0.55,
            "macro_1": 0.36,
            "macro_4": 0.24,
            "lfo1_depth": 0.16,
            "mod_env1_decay": 0.14,
            "mod_env1_depth": 0.38,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.14,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.07,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.03,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 130.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -3.0,
            "fx_eq_mid_gain": -0.4,
            "fx_eq_high_gain": 1.2,
            "fx_eq_trim": -0.7,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.18,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.1,
            "fx_tremolo_pan": 0.32,
            "fx_tremolo_shape": 0.42,
            "fx_tremolo_phase": 0.12,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.36,
            "fx_phaser_enabled": 1,
            "fx_phaser_mix": 0.1,
            "fx_guard_enabled": 1,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.36,
            "sequencer_swing": 0.18,
            "sequencer_groove_mode": 1,
            "sequencer_accent": 0.48,
            "sequencer_probability": 0.94,
            "sequencer_random_amount": 0.3,
            "random_recipe": 8,
        },
        "steps": sequence(
            step(2, 0, 0.72, 1.0, 0.12),
            step(6, 7, 0.86, 0.95, 0.24),
            step(10, 3, 0.76, 0.9, 0.18),
            step(14, 10, 0.9, 0.85, 0.32),
        ),
    },
    {
        "name": "UKG Bell Pluck",
        "params": {
            "osc_wave": 3,
            "osc_octave": 1,
            "osc1_level": 0.72,
            "osc2_wave": 0,
            "osc2_octave": 1,
            "osc2_tune": 12.0,
            "osc2_level": 0.38,
            "amp_attack": 0.002,
            "amp_decay": 0.08,
            "amp_sustain": 0.0,
            "amp_release": 0.22,
            "filter_cutoff": 7200.0,
            "filter_resonance": 0.55,
            "filter_env_amount": 0.42,
            "drive_amount": 0.08,
            "unison_voices": 2,
            "unison_detune": 0.03,
            "unison_spread": 0.42,
            "macro_1": 0.48,
            "macro_4": 0.34,
            "lfo1_sync_rate": 2,
            "lfo1_depth": 0.14,
            "mod_env1_decay": 0.08,
            "mod_env1_depth": 0.5,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.2,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 2,
            "mod_slot_2_amount": 0.08,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 150.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -4.0,
            "fx_eq_mid_gain": -0.8,
            "fx_eq_high_gain": 1.8,
            "fx_eq_trim": -0.9,
            "fx_delay_enabled": 1,
            "fx_delay_time": 0.18,
            "fx_delay_feedback": 0.22,
            "fx_delay_mix": 0.16,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 2,
            "fx_tremolo_depth": 0.14,
            "fx_tremolo_pan": 0.38,
            "fx_tremolo_shape": 0.35,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 186.0,
            "fx_ring_depth": 0.24,
            "fx_ring_mix": 0.08,
            "fx_ring_bias": 0.38,
            "fx_reverb_enabled": 1,
            "fx_reverb_size": 0.28,
            "fx_reverb_mix": 0.14,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.42,
            "fx_guard_enabled": 1,
            "output_gain": -10.5,
            "random_recipe": 9,
        },
        "steps": blank_steps(),
    },
    {
        "name": "UKG Vocal Chop Starter",
        "params": {
            "sample_enabled": 0,
            "sample_playback_mode": 1,
            "sample_start": 0.12,
            "sample_end": 0.22,
            "sample_transpose": 7.0,
            "sample_pitch_ramp": -7.0,
            "sample_gain": -5.0,
            "sample_mix": 0.9,
            "sample_stutter_enabled": 1,
            "sample_stutter_rate": 1,
            "sample_stutter_repeats": 4,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.22,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 3,
            "fx_tremolo_depth": 0.22,
            "fx_tremolo_pan": 0.44,
            "fx_tremolo_shape": 0.62,
            "fx_tremolo_phase": 0.18,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 92.0,
            "fx_ring_depth": 0.18,
            "fx_ring_mix": 0.06,
            "fx_ring_bias": 0.62,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.8,
            "fx_eq_mid_gain": 0.2,
            "fx_eq_high_gain": 1.4,
            "fx_eq_trim": -0.8,
            "fx_delay_enabled": 1,
            "fx_delay_time": 0.16,
            "fx_delay_feedback": 0.18,
            "fx_delay_mix": 0.12,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.22,
            "fx_guard_enabled": 1,
            "output_gain": -9.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.2,
            "sequencer_swing": 0.46,
            "sequencer_groove_mode": 2,
            "sequencer_accent": 0.46,
            "sequencer_probability": 0.84,
            "sequencer_random_amount": 0.62,
        },
        "steps": sequence(
            step(1, 0, 0.72, 0.9, 0.68),
            step(4, 7, 0.86, 1.0),
            step(6, -5, 0.58, 0.68, 0.28),
            step(9, 3, 0.78, 0.86, 0.74),
            step(12, 0, 0.7, 0.78),
            step(14, 12, 0.82, 0.82, 0.36),
        ),
    },
    {
        "name": "UKG Late Stab",
        "params": {
            "osc_wave": 1,
            "osc_octave": 0,
            "osc1_level": 0.78,
            "osc2_wave": 2,
            "osc2_octave": 0,
            "osc2_tune": 3.0,
            "osc2_level": 0.42,
            "amp_attack": 0.004,
            "amp_decay": 0.2,
            "amp_sustain": 0.16,
            "amp_release": 0.18,
            "filter_cutoff": 2500.0,
            "filter_resonance": 0.4,
            "filter_env_amount": 0.28,
            "drive_amount": 0.2,
            "unison_voices": 2,
            "unison_detune": 0.06,
            "unison_spread": 0.46,
            "macro_1": 0.24,
            "macro_2": 0.1,
            "lfo1_depth": 0.16,
            "mod_env1_decay": 0.2,
            "mod_env1_depth": 0.36,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.13,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.05,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": -0.025,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 105.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.4,
            "fx_eq_mid_gain": 0.1,
            "fx_eq_high_gain": 0.9,
            "fx_eq_trim": -0.6,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.14,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.09,
            "fx_tremolo_pan": 0.26,
            "fx_tremolo_shape": 0.45,
            "fx_tremolo_phase": 0.08,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 128.0,
            "fx_ring_depth": 0.16,
            "fx_ring_mix": 0.05,
            "fx_ring_bias": 0.5,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.28,
            "fx_reverb_enabled": 1,
            "fx_reverb_mix": 0.12,
            "fx_guard_enabled": 1,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.28,
            "sequencer_swing": 0.38,
            "sequencer_groove_mode": 1,
            "sequencer_accent": 0.52,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.34,
            "random_recipe": 8,
        },
        "steps": sequence(
            step(3, 0, 0.76, 1.0, 0.82),
            step(7, 7, 0.86, 0.92, 1.0),
            step(10, 3, 0.66, 0.72, 0.34),
            step(15, 10, 0.82, 0.86, 0.9),
        ),
    },
]


def value_string(value):
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def write_preset(preset):
    params = DEFAULTS | preset["params"]
    root = ElementTree.Element(
        "PARAMETERS",
        {
            "nate_vst_state_version": "1",
            "sample_file": "",
            "preset_name": preset["name"],
            "preset_category": "UKG",
            "preset_author": "Nate",
            "preset_source": "Factory",
            **preset["steps"],
        },
    )

    for param_id, value in params.items():
        ElementTree.SubElement(root, "PARAM", {"id": param_id, "value": value_string(value)})

    tree = ElementTree.ElementTree(root)
    ElementTree.indent(tree, space="  ")
    destination = OUTPUT_DIR / f"{preset['name']}.natevstpreset"
    tree.write(destination, encoding="utf-8", xml_declaration=True)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for preset in PRESETS:
        write_preset(preset)


if __name__ == "__main__":
    main()
