#!/usr/bin/env python3

from pathlib import Path
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "Resources" / "Factory Presets"


DEFAULTS = {
    "osc_wave": 1,
    "osc_octave": 0,
    "osc_tune": 0.0,
    "osc1_level": 1.0,
    "osc2_wave": 1,
    "osc2_octave": 0,
    "osc2_tune": 0.0,
    "osc2_level": 0.0,
    "sub_level": 0.0,
    "noise_level": 0.0,
    "osc_warp": 0.0,
    "amp_attack": 0.01,
    "amp_decay": 0.18,
    "amp_sustain": 0.65,
    "amp_release": 0.22,
    "filter_cutoff": 1800.0,
    "filter_resonance": 0.45,
    "filter_env_amount": 0.15,
    "filter_mode": 0,
    "filter_character": 0,
    "filter_slope": 0,
    "drive_amount": 0.18,
    "output_gain": -8.0,
    "mono_mode": 0,
    "glide_time": 0.0,
    "unison_voices": 1,
    "unison_detune": 0.0,
    "unison_blend": 0.65,
    "unison_spread": 0.0,
    "macro_1": 0.0,
    "macro_2": 0.0,
    "macro_3": 0.0,
    "macro_4": 0.0,
    "macro_5": 0.0,
    "macro_6": 0.0,
    "macro_7": 0.0,
    "macro_8": 0.0,
    "lfo1_rate": 1.0,
    "lfo1_sync": 1,
    "lfo1_sync_rate": 1,
    "lfo1_shape": 0,
    "lfo1_depth": 0.45,
    "lfo1_phase": 0.0,
    "lfo1_retrigger": 1,
    "lfo1_curve_1": 0.0,
    "lfo1_curve_2": 0.58,
    "lfo1_curve_3": 1.0,
    "lfo1_curve_4": 0.42,
    "lfo1_curve_5": -0.18,
    "lfo1_curve_6": -0.72,
    "lfo1_curve_7": -1.0,
    "lfo1_curve_8": -0.36,
    "lfo2_rate": 1.5,
    "lfo2_sync": 1,
    "lfo2_sync_rate": 3,
    "lfo2_shape": 1,
    "lfo2_depth": 0.25,
    "lfo2_phase": 0.25,
    "lfo2_retrigger": 1,
    "mod_env1_attack": 0.01,
    "mod_env1_decay": 0.22,
    "mod_env1_sustain": 0.0,
    "mod_env1_release": 0.12,
    "mod_env1_depth": 0.5,
    "mod_slot_1_enabled": 1,
    "mod_slot_2_enabled": 1,
    "mod_slot_3_enabled": 1,
    "mod_slot_4_enabled": 1,
    "mod_slot_5_enabled": 1,
    "mod_slot_6_enabled": 1,
    "mod_slot_7_enabled": 1,
    "mod_slot_8_enabled": 1,
    "random_amount": 0.45,
    "random_chaos": 0.25,
    "random_brightness_bias": 0.0,
    "random_drive_bias": 0.0,
    "random_motion_bias": 0.0,
    "random_recipe": 6,
    "random_lock_pitch": 0,
    "random_lock_envelope": 0,
    "random_lock_filter": 0,
    "random_lock_source": 0,
    "random_lock_sample": 0,
    "random_lock_fx": 0,
    "random_lock_output": 0,
    "random_lock_sequencer": 0,
    "sample_enabled": 0,
    "sample_start": 0.0,
    "sample_end": 1.0,
    "sample_reverse": 0,
    "sample_playback_mode": 1,
    "sample_transpose": 0.0,
    "sample_pitch_ramp": 0.0,
    "sample_gain": -6.0,
    "sample_mix": 0.75,
    "sample_stutter_enabled": 0,
    "sample_stutter_rate": 1,
    "sample_stutter_repeats": 3,
    "sample_slice_style": 0,
    "sequencer_enabled": 0,
    "sequencer_rate": 1,
    "sequencer_root": 36,
    "sequencer_gate": 0.55,
    "sequencer_swing": 0.0,
    "sequencer_groove_mode": 0,
    "sequencer_scale": 0,
    "sequencer_chord_mode": 0,
    "sequencer_chord_voicing": 0,
    "sequencer_chord_strum": 0.0,
    "sequencer_chord_memory": 0,
    "sequencer_accent": 0.35,
    "sequencer_octave": 0,
    "sequencer_probability": 1.0,
    "sequencer_random_amount": 0.55,
    "fx_distortion_enabled": 0,
    "fx_distortion_amount": 0.2,
    "fx_bitcrush_enabled": 0,
    "fx_bitcrush_bits": 12.0,
    "fx_bitcrush_downsample": 1.0,
    "fx_bitcrush_mix": 0.25,
    "fx_pump_enabled": 0,
    "fx_pump_rate": 0,
    "fx_pump_curve": 0,
    "fx_pump_curve_1": 1.0,
    "fx_pump_curve_2": 0.82,
    "fx_pump_curve_3": 0.62,
    "fx_pump_curve_4": 0.44,
    "fx_pump_curve_5": 0.28,
    "fx_pump_curve_6": 0.16,
    "fx_pump_curve_7": 0.07,
    "fx_pump_curve_8": 0.0,
    "fx_pump_depth": 0.35,
    "fx_pump_shape": 0.45,
    "fx_pump_phase": 0.0,
    "fx_tremolo_enabled": 0,
    "fx_tremolo_rate": 1,
    "fx_tremolo_depth": 0.28,
    "fx_tremolo_pan": 0.25,
    "fx_tremolo_shape": 0.45,
    "fx_tremolo_phase": 0.0,
    "fx_ring_enabled": 0,
    "fx_ring_frequency": 72.0,
    "fx_ring_depth": 0.35,
    "fx_ring_mix": 0.18,
    "fx_ring_bias": 0.45,
    "fx_comb_enabled": 0,
    "fx_comb_frequency": 180.0,
    "fx_comb_feedback": 0.28,
    "fx_comb_damping": 0.35,
    "fx_comb_mix": 0.16,
    "fx_chorus_enabled": 0,
    "fx_chorus_rate": 0.35,
    "fx_chorus_depth": 0.35,
    "fx_chorus_mix": 0.25,
    "fx_delay_enabled": 0,
    "fx_delay_sync": 0,
    "fx_delay_rate": 1,
    "fx_delay_time": 0.25,
    "fx_delay_feedback": 0.25,
    "fx_delay_mix": 0.2,
    "fx_reverb_enabled": 0,
    "fx_reverb_size": 0.35,
    "fx_reverb_damping": 0.45,
    "fx_reverb_mix": 0.2,
    "fx_width_enabled": 0,
    "fx_width_amount": 1.15,
    "fx_width_mono_cutoff": 120.0,
    "fx_tone_enabled": 0,
    "fx_tone_tilt": 0.0,
    "fx_tone_low_cut": 30.0,
    "fx_eq_enabled": 0,
    "fx_eq_low_gain": 0.0,
    "fx_eq_mid_gain": 0.0,
    "fx_eq_high_gain": 0.0,
    "fx_eq_trim": 0.0,
    "fx_phaser_enabled": 0,
    "fx_phaser_rate": 0.32,
    "fx_phaser_depth": 0.42,
    "fx_phaser_mix": 0.22,
    "fx_guard_enabled": 0,
    "fx_guard_push": 0.0,
    "fx_guard_ceiling": 0.92,
    "fx_flanger_enabled": 0,
    "fx_flanger_rate": 0.22,
    "fx_flanger_depth": 0.32,
    "fx_flanger_feedback": 0.18,
    "fx_flanger_mix": 0.18,
}

for slot_index in range(1, 9):
    DEFAULTS[f"mod_slot_{slot_index}_source"] = 0
    DEFAULTS[f"mod_slot_{slot_index}_destination"] = 0
    DEFAULTS[f"mod_slot_{slot_index}_amount"] = 0.0

for slice_index in range(1, 9):
    DEFAULTS[f"sample_slice_{slice_index}_custom"] = 0
    DEFAULTS[f"sample_slice_{slice_index}_start"] = (slice_index - 1) / 8.0
    DEFAULTS[f"sample_slice_{slice_index}_end"] = slice_index / 8.0
    DEFAULTS[f"sample_slice_{slice_index}_reverse"] = 0
    DEFAULTS[f"sample_slice_{slice_index}_transpose"] = 0.0
    DEFAULTS[f"sample_slice_{slice_index}_gain"] = -6.0
    DEFAULTS[f"sample_slice_{slice_index}_pan"] = 0.0
    DEFAULTS[f"sample_slice_{slice_index}_probability"] = 1.0
    DEFAULTS[f"sample_slice_{slice_index}_stutter"] = 0
    DEFAULTS[f"sample_slice_{slice_index}_choke"] = 0
    DEFAULTS[f"sample_slice_{slice_index}_stutter_repeats"] = 3

for slot_index in range(1, 16):
    DEFAULTS[f"fx_order_{slot_index}"] = slot_index - 1


FILTER_CHARACTER_BY_PRESET = {
    "UKG 2-Step Bass": 1,
    "UKG Shuffle Bass": 1,
    "UKG Dred Bass": 3,
    "UKG Organ Stab": 1,
    "UKG Chord Stab": 1,
    "UKG Bell Pluck": 0,
    "UKG Vocal Chop Starter": 1,
    "UKG Late Stab": 1,
    "House Chord Memory": 1,
    "Deep House Sub Chug": 1,
    "Tech House Rubber Bass": 2,
    "Tech House Perc Pluck": 1,
    "Minimal Click Pluck": 0,
    "Minimal Sub Pulse": 1,
    "Techno Pulse Bass": 2,
    "Techno Warehouse Stab": 3,
}


FILTER_SLOPE_BY_PRESET = {
    "UKG 2-Step Bass": 1,
    "UKG Shuffle Bass": 1,
    "UKG Dred Bass": 1,
    "UKG Organ Stab": 0,
    "UKG Chord Stab": 0,
    "UKG Bell Pluck": 0,
    "UKG Vocal Chop Starter": 0,
    "UKG Late Stab": 0,
    "House Chord Memory": 0,
    "Deep House Sub Chug": 1,
    "Tech House Rubber Bass": 1,
    "Tech House Perc Pluck": 0,
    "Minimal Click Pluck": 0,
    "Minimal Sub Pulse": 1,
    "Techno Pulse Bass": 1,
    "Techno Warehouse Stab": 1,
}


OSC_WARP_BY_PRESET = {
    "UKG 2-Step Bass": 0.16,
    "UKG Shuffle Bass": 0.18,
    "UKG Dred Bass": 0.24,
    "UKG Organ Stab": 0.12,
    "UKG Chord Stab": 0.14,
    "UKG Bell Pluck": 0.04,
    "UKG Vocal Chop Starter": 0.08,
    "UKG Late Stab": 0.16,
    "House Chord Memory": 0.1,
    "Deep House Sub Chug": 0.12,
    "Tech House Rubber Bass": 0.22,
    "Tech House Perc Pluck": 0.12,
    "Minimal Click Pluck": 0.18,
    "Minimal Sub Pulse": 0.1,
    "Techno Pulse Bass": 0.24,
    "Techno Warehouse Stab": 0.28,
}


FACTORY_METADATA = {
    "UKG 2-Step Bass": {"pack": "UKG Essentials", "key": "D Min", "bpm": 132},
    "UKG Shuffle Bass": {"pack": "UKG Essentials", "key": "C Min", "bpm": 134},
    "UKG Dred Bass": {"pack": "UKG Basslines", "key": "C# Min", "bpm": 132},
    "UKG Organ Stab": {"pack": "UKG Essentials", "key": "F Min", "bpm": 132},
    "UKG Chord Stab": {"pack": "UKG Essentials", "key": "G Min", "bpm": 130},
    "UKG Bell Pluck": {"pack": "UKG Essentials", "key": "C Min", "bpm": 132},
    "UKG Vocal Chop Starter": {"pack": "Garage Chops", "key": "A Min", "bpm": 134},
    "UKG Late Stab": {"pack": "UKG Essentials", "key": "F Min", "bpm": 132},
    "House Chord Memory": {"pack": "House Tools", "key": "C Min", "bpm": 124},
    "Deep House Sub Chug": {"pack": "House Tools", "key": "F Min", "bpm": 124},
    "Tech House Rubber Bass": {"pack": "Tech House Tools", "key": "F# Min", "bpm": 126},
    "Tech House Perc Pluck": {"pack": "Tech House Tools", "key": "A Min", "bpm": 126},
    "Minimal Click Pluck": {"pack": "Minimal Tools", "key": "D Min", "bpm": 126},
    "Minimal Sub Pulse": {"pack": "Minimal Tools", "key": "E Min", "bpm": 126},
    "Techno Pulse Bass": {"pack": "Techno Tools", "key": "F Min", "bpm": 132},
    "Techno Warehouse Stab": {"pack": "Techno Tools", "key": "C Min", "bpm": 132},
}


def step(index, note, velocity, probability, timing=0.0, length=1.0):
    return {
        f"seq_step_{index}_enabled": "1",
        f"seq_step_{index}_note": str(note),
        f"seq_step_{index}_velocity": str(velocity),
        f"seq_step_{index}_probability": str(probability),
        f"seq_step_{index}_timing": str(timing),
        f"seq_step_{index}_length": str(length),
    }


def blank_steps():
    props = {}
    for index in range(16):
        props[f"seq_step_{index}_enabled"] = "0"
        props[f"seq_step_{index}_note"] = "0"
        props[f"seq_step_{index}_velocity"] = "0.8"
        props[f"seq_step_{index}_probability"] = "1"
        props[f"seq_step_{index}_timing"] = "0"
        props[f"seq_step_{index}_length"] = "1"
    return props


def sequence(*steps):
    props = blank_steps()
    for item in steps:
        props.update(item)
    return props


def curve(*values):
    return {f"lfo1_curve_{index + 1}": value for index, value in enumerate(values)}


TAG_ORDER = [
    "House",
    "Tech House",
    "Techno",
    "Minimal",
    "UKG",
    "Bass",
    "Chord",
    "Pluck",
    "Stab",
    "Sequenced",
    "Mono Safe",
    "Pump",
    "Wide",
    "FX",
    "Vocal Chop",
    "Sample",
    "Guard",
]


def preset_tags(preset, params):
    name = preset["name"].lower()
    category = preset.get("category", "UKG")
    tags = {category}

    if "bass" in name or params.get("sub_level", 0.0) >= 0.35:
        tags.add("Bass")
    if "chord" in name or params.get("sequencer_chord_mode", 0) >= 2:
        tags.add("Chord")
    if "pluck" in name or "bell" in name:
        tags.add("Pluck")
    if "stab" in name or params.get("sequencer_chord_mode", 0) > 0:
        tags.add("Stab")
    if "vocal" in name or "chop" in name:
        tags.add("Vocal Chop")
    if params.get("sample_enabled", 0) or "sample" in name:
        tags.add("Sample")
    if params.get("sequencer_enabled", 0):
        tags.add("Sequenced")
    if params.get("mono_mode", 0) or (params.get("fx_width_enabled", 0) and params.get("fx_width_mono_cutoff", 0.0) >= 100.0):
        tags.add("Mono Safe")
    if params.get("fx_pump_enabled", 0):
        tags.add("Pump")
    if params.get("fx_width_enabled", 0) and params.get("fx_width_amount", 1.0) > 1.05:
        tags.add("Wide")
    if params.get("fx_guard_enabled", 0):
        tags.add("Guard")

    fx_enabled = [
        "fx_distortion_enabled",
        "fx_bitcrush_enabled",
        "fx_tremolo_enabled",
        "fx_ring_enabled",
        "fx_comb_enabled",
        "fx_chorus_enabled",
        "fx_delay_enabled",
        "fx_reverb_enabled",
        "fx_phaser_enabled",
        "fx_flanger_enabled",
    ]
    if any(params.get(param, 0) for param in fx_enabled):
        tags.add("FX")

    return ", ".join(tag for tag in TAG_ORDER if tag in tags)


PRESETS = [
    {
        "name": "UKG 2-Step Bass",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.86,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.12,
            "osc2_level": 0.32,
            "sub_level": 0.62,
            "amp_attack": 0.004,
            "amp_decay": 0.18,
            "amp_sustain": 0.38,
            "amp_release": 0.09,
            "filter_cutoff": 980.0,
            "filter_resonance": 0.38,
            "filter_env_amount": 0.32,
            "drive_amount": 0.22,
            "mono_mode": 1,
            "glide_time": 0.055,
            "macro_1": 0.18,
            "macro_2": 0.12,
            "macro_3": 0.24,
            "lfo1_shape": 5,
            "lfo1_depth": 0.2,
            **curve(0.02, 0.7, 0.95, 0.36, -0.08, -0.42, -0.78, -0.24),
            "mod_env1_decay": 0.16,
            "mod_env1_depth": 0.34,
            "mod_slot_1_source": 1,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.08,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 3,
            "mod_slot_2_amount": 0.07,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 34.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.2,
            "fx_eq_mid_gain": -1.4,
            "fx_eq_high_gain": -0.4,
            "fx_eq_trim": -0.7,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 12.0,
            "fx_bitcrush_downsample": 2.0,
            "fx_bitcrush_mix": 0.08,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.28,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.02,
            "fx_width_mono_cutoff": 160.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.08,
            "fx_guard_ceiling": 0.91,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 38,
            "sequencer_gate": 0.34,
            "sequencer_swing": 0.42,
            "sequencer_groove_mode": 2,
            "sequencer_scale": 4,
            "sequencer_chord_mode": 0,
            "sequencer_chord_voicing": 0,
            "sequencer_chord_strum": 0.0,
            "sequencer_accent": 0.58,
            "sequencer_octave": -1,
            "sequencer_probability": 0.93,
            "sequencer_random_amount": 0.48,
            "random_recipe": 6,
        },
        "steps": sequence(
            step(0, 0, 0.88, 1.0),
            step(2, 7, 0.62, 0.85, 0.18),
            step(5, 3, 0.78, 0.95, 0.72),
            step(7, 10, 0.54, 0.72, 0.86),
            step(9, 0, 0.82, 1.0),
            step(11, -5, 0.66, 0.82, 0.78),
            step(14, 7, 0.76, 0.92, 0.26),
        ),
    },
    {
        "name": "UKG Shuffle Bass",
        "params": {
            "osc_wave": 2,
            "osc_octave": -1,
            "osc1_level": 0.82,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": 0.1,
            "osc2_level": 0.28,
            "sub_level": 0.58,
            "amp_attack": 0.004,
            "amp_decay": 0.16,
            "amp_sustain": 0.28,
            "amp_release": 0.08,
            "filter_cutoff": 760.0,
            "filter_resonance": 0.48,
            "filter_env_amount": 0.4,
            "drive_amount": 0.26,
            "mono_mode": 1,
            "glide_time": 0.075,
            "macro_3": 0.28,
            "lfo1_shape": 5,
            "lfo1_depth": 0.24,
            **curve(-0.04, 0.62, 1.0, 0.28, -0.12, -0.5, -0.86, -0.18),
            "mod_env1_decay": 0.14,
            "mod_env1_depth": 0.38,
            "mod_slot_1_source": 1,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.1,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 3,
            "mod_slot_2_amount": 0.09,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 32.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.0,
            "fx_eq_mid_gain": -1.8,
            "fx_eq_high_gain": -0.5,
            "fx_eq_trim": -0.8,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.34,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.0,
            "fx_width_mono_cutoff": 165.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.07,
            "fx_guard_ceiling": 0.9,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.3,
            "sequencer_swing": 0.5,
            "sequencer_groove_mode": 2,
            "sequencer_scale": 4,
            "sequencer_chord_mode": 0,
            "sequencer_chord_voicing": 0,
            "sequencer_chord_strum": 0.0,
            "sequencer_accent": 0.6,
            "sequencer_octave": -1,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.52,
            "random_recipe": 6,
        },
        "steps": sequence(
            step(0, 0, 0.9, 1.0),
            step(3, 7, 0.62, 0.76, 0.82),
            step(5, -5, 0.74, 0.9, 0.7),
            step(8, 0, 0.84, 1.0),
            step(10, 3, 0.56, 0.68, 0.24),
            step(13, -2, 0.78, 0.86, 0.76),
            step(15, 7, 0.52, 0.62, 0.88),
        ),
    },
    {
        "name": "UKG Dred Bass",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.88,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.09,
            "osc2_level": 0.42,
            "sub_level": 0.66,
            "amp_attack": 0.006,
            "amp_decay": 0.34,
            "amp_sustain": 0.32,
            "amp_release": 0.13,
            "filter_cutoff": 420.0,
            "filter_resonance": 0.58,
            "filter_env_amount": 0.5,
            "drive_amount": 0.32,
            "mono_mode": 1,
            "glide_time": 0.085,
            "unison_voices": 2,
            "unison_detune": 0.045,
            "unison_blend": 0.42,
            "unison_spread": 0.06,
            "macro_2": 0.2,
            "macro_3": 0.36,
            "lfo1_shape": 5,
            "lfo1_depth": 0.26,
            **curve(-0.16, 0.18, 0.78, 1.0, 0.44, -0.05, -0.48, -0.26),
            "mod_env1_attack": 0.09,
            "mod_env1_decay": 0.34,
            "mod_env1_sustain": 0.12,
            "mod_env1_release": 0.12,
            "mod_env1_depth": 0.52,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.24,
            "mod_slot_2_source": 1,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.08,
            "mod_slot_3_source": 2,
            "mod_slot_3_destination": 3,
            "mod_slot_3_amount": 0.13,
            "mod_slot_4_source": 13,
            "mod_slot_4_destination": 17,
            "mod_slot_4_amount": 0.035,
            "fx_tone_enabled": 1,
            "fx_tone_tilt": -0.14,
            "fx_tone_low_cut": 34.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.4,
            "fx_eq_mid_gain": -1.6,
            "fx_eq_high_gain": -0.8,
            "fx_eq_trim": -0.9,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 12.0,
            "fx_bitcrush_downsample": 2.5,
            "fx_bitcrush_mix": 0.09,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.32,
            "fx_pump_shape": 0.58,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.02,
            "fx_width_mono_cutoff": 170.0,
            "fx_phaser_enabled": 1,
            "fx_phaser_rate": 0.16,
            "fx_phaser_depth": 0.38,
            "fx_phaser_mix": 0.1,
            "fx_flanger_enabled": 1,
            "fx_flanger_rate": 0.11,
            "fx_flanger_depth": 0.24,
            "fx_flanger_feedback": 0.12,
            "fx_flanger_mix": 0.06,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.09,
            "fx_guard_ceiling": 0.9,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 37,
            "sequencer_gate": 0.32,
            "sequencer_swing": 0.48,
            "sequencer_groove_mode": 2,
            "sequencer_scale": 4,
            "sequencer_chord_mode": 0,
            "sequencer_chord_voicing": 0,
            "sequencer_chord_strum": 0.0,
            "sequencer_accent": 0.62,
            "sequencer_octave": -1,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.5,
            "random_recipe": 10,
        },
        "steps": sequence(
            step(0, 0, 0.9, 1.0),
            step(3, -5, 0.58, 0.72, 0.84),
            step(5, 7, 0.76, 0.92, 0.72),
            step(8, 0, 0.84, 1.0),
            step(11, 3, 0.62, 0.78, 0.8),
            step(13, -2, 0.74, 0.86, 0.68),
            step(15, 7, 0.52, 0.66, 0.92),
        ),
    },
    {
        "name": "UKG Organ Stab",
        "params": {
            "osc_wave": 2,
            "osc_octave": 0,
            "osc1_level": 0.78,
            "osc2_wave": 3,
            "osc2_octave": 0,
            "osc2_tune": 0.08,
            "osc2_level": 0.46,
            "sub_level": 0.08,
            "amp_attack": 0.003,
            "amp_decay": 0.18,
            "amp_sustain": 0.34,
            "amp_release": 0.1,
            "filter_cutoff": 2800.0,
            "filter_resonance": 0.3,
            "filter_env_amount": 0.2,
            "drive_amount": 0.12,
            "unison_voices": 2,
            "unison_detune": 0.04,
            "unison_spread": 0.34,
            "macro_1": 0.28,
            "macro_4": 0.18,
            "lfo1_depth": 0.18,
            "mod_env1_decay": 0.18,
            "mod_env1_depth": 0.42,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.15,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.06,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.025,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 110.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.6,
            "fx_eq_mid_gain": 0.3,
            "fx_eq_high_gain": 1.0,
            "fx_eq_trim": -0.5,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.16,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.12,
            "fx_tremolo_pan": 0.28,
            "fx_tremolo_shape": 0.48,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.26,
            "fx_chorus_enabled": 1,
            "fx_chorus_depth": 0.22,
            "fx_chorus_mix": 0.16,
            "fx_guard_enabled": 1,
            "fx_guard_ceiling": 0.94,
            "output_gain": -9.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.24,
            "sequencer_swing": 0.34,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 2,
            "sequencer_chord_mode": 3,
            "sequencer_chord_voicing": 3,
            "sequencer_chord_strum": 0.22,
            "sequencer_accent": 0.56,
            "sequencer_probability": 0.92,
            "sequencer_random_amount": 0.38,
            "random_recipe": 7,
        },
        "steps": sequence(
            step(2, 0, 0.76, 1.0, 0.22),
            step(6, 3, 0.88, 0.95, 0.34),
            step(10, 7, 0.72, 0.88, 0.26),
            step(14, 10, 0.84, 0.86, 0.42),
        ),
    },
    {
        "name": "UKG Chord Stab",
        "params": {
            "osc_wave": 1,
            "osc_octave": 0,
            "osc1_level": 0.74,
            "osc2_wave": 1,
            "osc2_octave": 0,
            "osc2_tune": 7.0,
            "osc2_level": 0.58,
            "amp_attack": 0.003,
            "amp_decay": 0.14,
            "amp_sustain": 0.08,
            "amp_release": 0.14,
            "filter_cutoff": 4200.0,
            "filter_resonance": 0.34,
            "filter_env_amount": 0.24,
            "drive_amount": 0.18,
            "unison_voices": 3,
            "unison_detune": 0.08,
            "unison_spread": 0.55,
            "macro_1": 0.36,
            "macro_4": 0.24,
            "lfo1_depth": 0.16,
            "mod_env1_decay": 0.14,
            "mod_env1_depth": 0.38,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.14,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.07,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.03,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 130.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -3.0,
            "fx_eq_mid_gain": -0.4,
            "fx_eq_high_gain": 1.2,
            "fx_eq_trim": -0.7,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.18,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.1,
            "fx_tremolo_pan": 0.32,
            "fx_tremolo_shape": 0.42,
            "fx_tremolo_phase": 0.12,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.36,
            "fx_phaser_enabled": 1,
            "fx_phaser_mix": 0.1,
            "fx_guard_enabled": 1,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.36,
            "sequencer_swing": 0.18,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 2,
            "sequencer_chord_mode": 4,
            "sequencer_chord_voicing": 1,
            "sequencer_chord_strum": 0.12,
            "sequencer_accent": 0.48,
            "sequencer_probability": 0.94,
            "sequencer_random_amount": 0.3,
            "random_recipe": 8,
        },
        "steps": sequence(
            step(2, 0, 0.72, 1.0, 0.12),
            step(6, 7, 0.86, 0.95, 0.24),
            step(10, 3, 0.76, 0.9, 0.18),
            step(14, 10, 0.9, 0.85, 0.32),
        ),
    },
    {
        "name": "UKG Bell Pluck",
        "params": {
            "osc_wave": 3,
            "osc_octave": 1,
            "osc1_level": 0.72,
            "osc2_wave": 0,
            "osc2_octave": 1,
            "osc2_tune": 12.0,
            "osc2_level": 0.38,
            "amp_attack": 0.002,
            "amp_decay": 0.08,
            "amp_sustain": 0.0,
            "amp_release": 0.22,
            "filter_cutoff": 7200.0,
            "filter_resonance": 0.55,
            "filter_env_amount": 0.42,
            "drive_amount": 0.08,
            "unison_voices": 2,
            "unison_detune": 0.03,
            "unison_spread": 0.42,
            "macro_1": 0.48,
            "macro_4": 0.34,
            "lfo1_sync_rate": 2,
            "lfo1_depth": 0.14,
            "mod_env1_decay": 0.08,
            "mod_env1_depth": 0.5,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.2,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 2,
            "mod_slot_2_amount": 0.08,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 150.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -4.0,
            "fx_eq_mid_gain": -0.8,
            "fx_eq_high_gain": 1.8,
            "fx_eq_trim": -0.9,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 3,
            "fx_delay_time": 0.18,
            "fx_delay_feedback": 0.22,
            "fx_delay_mix": 0.16,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 2,
            "fx_tremolo_depth": 0.14,
            "fx_tremolo_pan": 0.38,
            "fx_tremolo_shape": 0.35,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 186.0,
            "fx_ring_depth": 0.24,
            "fx_ring_mix": 0.08,
            "fx_ring_bias": 0.38,
            "fx_comb_enabled": 1,
            "fx_comb_frequency": 420.0,
            "fx_comb_feedback": 0.22,
            "fx_comb_damping": 0.42,
            "fx_comb_mix": 0.08,
            "fx_reverb_enabled": 1,
            "fx_reverb_size": 0.28,
            "fx_reverb_mix": 0.14,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.42,
            "fx_guard_enabled": 1,
            "output_gain": -10.5,
            "random_recipe": 9,
        },
        "steps": blank_steps(),
    },
    {
        "name": "UKG Vocal Chop Starter",
        "params": {
            "sample_enabled": 0,
            "sample_playback_mode": 2,
            "sample_start": 0.12,
            "sample_end": 0.22,
            "sample_transpose": 7.0,
            "sample_pitch_ramp": -7.0,
            "sample_gain": -5.0,
            "sample_mix": 0.9,
            "sample_stutter_enabled": 1,
            "sample_stutter_rate": 1,
            "sample_stutter_repeats": 4,
            "sample_slice_style": 4,
            "mod_slot_1_source": 13,
            "mod_slot_1_destination": 12,
            "mod_slot_1_amount": 0.04,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.22,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 3,
            "fx_tremolo_depth": 0.22,
            "fx_tremolo_pan": 0.44,
            "fx_tremolo_shape": 0.62,
            "fx_tremolo_phase": 0.18,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 92.0,
            "fx_ring_depth": 0.18,
            "fx_ring_mix": 0.06,
            "fx_ring_bias": 0.62,
            "fx_comb_enabled": 1,
            "fx_comb_frequency": 280.0,
            "fx_comb_feedback": 0.18,
            "fx_comb_damping": 0.58,
            "fx_comb_mix": 0.06,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.8,
            "fx_eq_mid_gain": 0.2,
            "fx_eq_high_gain": 1.4,
            "fx_eq_trim": -0.8,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 2,
            "fx_delay_time": 0.16,
            "fx_delay_feedback": 0.18,
            "fx_delay_mix": 0.12,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.22,
            "fx_guard_enabled": 1,
            "output_gain": -9.0,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.2,
            "sequencer_swing": 0.46,
            "sequencer_groove_mode": 2,
            "sequencer_scale": 4,
            "sequencer_chord_mode": 0,
            "sequencer_chord_voicing": 0,
            "sequencer_chord_strum": 0.0,
            "sequencer_accent": 0.46,
            "sequencer_probability": 0.84,
            "sequencer_random_amount": 0.62,
        },
        "steps": sequence(
            step(1, 0, 0.72, 0.9, 0.68),
            step(4, 7, 0.86, 1.0),
            step(6, -5, 0.58, 0.68, 0.28),
            step(9, 3, 0.78, 0.86, 0.74),
            step(12, 0, 0.7, 0.78),
            step(14, 12, 0.82, 0.82, 0.36),
        ),
    },
    {
        "name": "UKG Late Stab",
        "params": {
            "osc_wave": 1,
            "osc_octave": 0,
            "osc1_level": 0.78,
            "osc2_wave": 2,
            "osc2_octave": 0,
            "osc2_tune": 3.0,
            "osc2_level": 0.42,
            "amp_attack": 0.004,
            "amp_decay": 0.2,
            "amp_sustain": 0.16,
            "amp_release": 0.18,
            "filter_cutoff": 2500.0,
            "filter_resonance": 0.4,
            "filter_env_amount": 0.28,
            "drive_amount": 0.2,
            "unison_voices": 2,
            "unison_detune": 0.06,
            "unison_spread": 0.46,
            "macro_1": 0.24,
            "macro_2": 0.1,
            "lfo1_depth": 0.16,
            "mod_env1_decay": 0.2,
            "mod_env1_depth": 0.36,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.13,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.05,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": -0.025,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 105.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.4,
            "fx_eq_mid_gain": 0.1,
            "fx_eq_high_gain": 0.9,
            "fx_eq_trim": -0.6,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.14,
            "fx_tremolo_enabled": 1,
            "fx_tremolo_rate": 1,
            "fx_tremolo_depth": 0.09,
            "fx_tremolo_pan": 0.26,
            "fx_tremolo_shape": 0.45,
            "fx_tremolo_phase": 0.08,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 128.0,
            "fx_ring_depth": 0.16,
            "fx_ring_mix": 0.05,
            "fx_ring_bias": 0.5,
            "fx_comb_enabled": 1,
            "fx_comb_frequency": 210.0,
            "fx_comb_feedback": 0.2,
            "fx_comb_damping": 0.5,
            "fx_comb_mix": 0.07,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.28,
            "fx_reverb_enabled": 1,
            "fx_reverb_mix": 0.12,
            "fx_guard_enabled": 1,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_gate": 0.28,
            "sequencer_swing": 0.38,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 2,
            "sequencer_chord_mode": 5,
            "sequencer_chord_voicing": 3,
            "sequencer_chord_strum": 0.32,
            "sequencer_accent": 0.52,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.34,
            "random_recipe": 8,
        },
        "steps": sequence(
            step(3, 0, 0.76, 1.0, 0.82),
            step(7, 7, 0.86, 0.92, 1.0),
            step(10, 3, 0.66, 0.72, 0.34),
            step(15, 10, 0.82, 0.86, 0.9),
        ),
    },
    {
        "name": "House Chord Memory",
        "category": "House",
        "params": {
            "osc_wave": 1,
            "osc_octave": 0,
            "osc1_level": 0.72,
            "osc2_wave": 3,
            "osc2_octave": 0,
            "osc2_tune": 0.05,
            "osc2_level": 0.38,
            "sub_level": 0.05,
            "amp_attack": 0.006,
            "amp_decay": 0.32,
            "amp_sustain": 0.24,
            "amp_release": 0.28,
            "filter_cutoff": 3300.0,
            "filter_resonance": 0.34,
            "filter_env_amount": 0.18,
            "drive_amount": 0.16,
            "unison_voices": 3,
            "unison_detune": 0.06,
            "unison_spread": 0.42,
            "macro_1": 0.34,
            "macro_2": 0.16,
            "macro_4": 0.32,
            "lfo1_depth": 0.12,
            "mod_env1_decay": 0.26,
            "mod_env1_depth": 0.34,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.1,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 1,
            "mod_slot_2_amount": 0.05,
            "mod_slot_3_source": 1,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.02,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 120.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -2.2,
            "fx_eq_mid_gain": -0.2,
            "fx_eq_high_gain": 1.1,
            "fx_eq_trim": -0.7,
            "fx_pump_enabled": 1,
            "fx_pump_depth": 0.18,
            "fx_pump_shape": 0.46,
            "fx_chorus_enabled": 1,
            "fx_chorus_rate": 0.28,
            "fx_chorus_depth": 0.28,
            "fx_chorus_mix": 0.16,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 2,
            "fx_delay_time": 0.22,
            "fx_delay_feedback": 0.18,
            "fx_delay_mix": 0.11,
            "fx_reverb_enabled": 1,
            "fx_reverb_size": 0.32,
            "fx_reverb_mix": 0.13,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.28,
            "fx_guard_enabled": 1,
            "fx_guard_ceiling": 0.94,
            "output_gain": -9.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 48,
            "sequencer_gate": 0.32,
            "sequencer_swing": 0.18,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 3,
            "sequencer_chord_mode": 3,
            "sequencer_chord_voicing": 4,
            "sequencer_chord_strum": 0.18,
            "sequencer_accent": 0.5,
            "sequencer_probability": 0.9,
            "sequencer_random_amount": 0.34,
            "random_recipe": 4,
        },
        "steps": sequence(
            step(2, 0, 0.78, 1.0, 0.12),
            step(6, 3, 0.86, 0.94, 0.2),
            step(10, 7, 0.74, 0.9, 0.14),
            step(14, 10, 0.84, 0.86, 0.24),
        ),
    },
    {
        "name": "Deep House Sub Chug",
        "category": "House",
        "params": {
            "osc_wave": 0,
            "osc_octave": -1,
            "osc1_level": 0.78,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.08,
            "osc2_level": 0.22,
            "sub_level": 0.72,
            "amp_attack": 0.004,
            "amp_decay": 0.42,
            "amp_sustain": 0.48,
            "amp_release": 0.18,
            "filter_cutoff": 720.0,
            "filter_resonance": 0.42,
            "filter_env_amount": 0.22,
            "drive_amount": 0.2,
            "mono_mode": 1,
            "glide_time": 0.035,
            "macro_1": 0.22,
            "macro_3": 0.18,
            "lfo1_shape": 5,
            "lfo1_depth": 0.16,
            **curve(0.0, 0.42, 0.86, 0.68, 0.2, -0.2, -0.55, -0.18),
            "mod_env1_decay": 0.3,
            "mod_env1_depth": 0.3,
            "mod_slot_1_source": 1,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.06,
            "mod_slot_2_source": 2,
            "mod_slot_2_destination": 3,
            "mod_slot_2_amount": 0.07,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 30.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.3,
            "fx_eq_mid_gain": -1.1,
            "fx_eq_high_gain": -0.5,
            "fx_eq_trim": -0.7,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 0,
            "fx_pump_depth": 0.2,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.03,
            "fx_width_mono_cutoff": 145.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.06,
            "fx_guard_ceiling": 0.91,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 36,
            "sequencer_gate": 0.42,
            "sequencer_swing": 0.22,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 4,
            "sequencer_accent": 0.64,
            "sequencer_octave": -1,
            "sequencer_probability": 0.94,
            "sequencer_random_amount": 0.42,
            "random_recipe": 0,
        },
        "steps": sequence(
            step(0, 0, 0.92, 1.0),
            step(3, 0, 0.64, 0.78, 0.44),
            step(5, -5, 0.78, 0.88, 0.18),
            step(7, 0, 0.58, 0.66, 0.26),
            step(10, 3, 0.74, 0.84, 0.18),
            step(12, 0, 0.88, 0.96),
            step(14, -2, 0.68, 0.78, 0.24),
            step(15, 0, 0.56, 0.62, 0.48),
        ),
    },
    {
        "name": "Tech House Rubber Bass",
        "category": "Tech House",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.86,
            "osc2_wave": 2,
            "osc2_octave": -1,
            "osc2_tune": 0.11,
            "osc2_level": 0.38,
            "sub_level": 0.42,
            "amp_attack": 0.003,
            "amp_decay": 0.22,
            "amp_sustain": 0.22,
            "amp_release": 0.08,
            "filter_cutoff": 980.0,
            "filter_resonance": 0.62,
            "filter_env_amount": 0.48,
            "drive_amount": 0.34,
            "mono_mode": 1,
            "glide_time": 0.06,
            "unison_voices": 2,
            "unison_detune": 0.035,
            "unison_blend": 0.36,
            "unison_spread": 0.08,
            "macro_2": 0.26,
            "macro_3": 0.28,
            "lfo1_shape": 5,
            "lfo1_depth": 0.18,
            **curve(-0.04, 0.5, 1.0, 0.3, -0.08, -0.38, -0.72, -0.16),
            "mod_env1_decay": 0.16,
            "mod_env1_depth": 0.44,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.18,
            "mod_slot_2_source": 1,
            "mod_slot_2_destination": 4,
            "mod_slot_2_amount": 0.05,
            "mod_slot_3_source": 13,
            "mod_slot_3_destination": 5,
            "mod_slot_3_amount": 0.025,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 36.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 0.8,
            "fx_eq_mid_gain": -0.8,
            "fx_eq_high_gain": 0.3,
            "fx_eq_trim": -0.8,
            "fx_distortion_enabled": 1,
            "fx_distortion_amount": 0.26,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 11.0,
            "fx_bitcrush_downsample": 2.0,
            "fx_bitcrush_mix": 0.08,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.3,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.04,
            "fx_width_mono_cutoff": 155.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.1,
            "fx_guard_ceiling": 0.9,
            "output_gain": -10.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 36,
            "sequencer_gate": 0.42,
            "sequencer_swing": 0.18,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 2,
            "sequencer_accent": 0.64,
            "sequencer_octave": -1,
            "sequencer_probability": 0.94,
            "sequencer_random_amount": 0.44,
            "random_recipe": 1,
        },
        "steps": sequence(
            step(0, 0, 0.92, 1.0),
            step(3, 0, 0.64, 0.78, 0.56),
            step(5, -5, 0.78, 0.88, 0.18),
            step(7, 0, 0.58, 0.66, 0.32),
            step(10, 3, 0.74, 0.84, 0.18),
            step(12, 0, 0.88, 0.96),
            step(14, -2, 0.68, 0.78, 0.24),
            step(15, 0, 0.56, 0.62, 0.48),
        ),
    },
    {
        "name": "Tech House Perc Pluck",
        "category": "Tech House",
        "params": {
            "osc_wave": 2,
            "osc_octave": 0,
            "osc1_level": 0.68,
            "osc2_wave": 3,
            "osc2_octave": 1,
            "osc2_tune": 7.0,
            "osc2_level": 0.32,
            "noise_level": 0.08,
            "amp_attack": 0.002,
            "amp_decay": 0.09,
            "amp_sustain": 0.0,
            "amp_release": 0.12,
            "filter_cutoff": 4200.0,
            "filter_resonance": 0.58,
            "filter_env_amount": 0.4,
            "drive_amount": 0.14,
            "macro_1": 0.4,
            "macro_2": 0.18,
            "macro_4": 0.24,
            "lfo1_sync_rate": 3,
            "lfo1_shape": 4,
            "lfo1_depth": 0.12,
            "mod_env1_decay": 0.08,
            "mod_env1_depth": 0.48,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.18,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 2,
            "mod_slot_2_amount": 0.05,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 130.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -3.2,
            "fx_eq_mid_gain": 0.4,
            "fx_eq_high_gain": 1.4,
            "fx_eq_trim": -0.8,
            "fx_comb_enabled": 1,
            "fx_comb_frequency": 310.0,
            "fx_comb_feedback": 0.2,
            "fx_comb_damping": 0.44,
            "fx_comb_mix": 0.1,
            "fx_ring_enabled": 1,
            "fx_ring_frequency": 118.0,
            "fx_ring_depth": 0.16,
            "fx_ring_mix": 0.06,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 4,
            "fx_delay_time": 0.14,
            "fx_delay_feedback": 0.16,
            "fx_delay_mix": 0.1,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.22,
            "fx_guard_enabled": 1,
            "output_gain": -10.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 48,
            "sequencer_gate": 0.18,
            "sequencer_swing": 0.3,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 4,
            "sequencer_accent": 0.42,
            "sequencer_probability": 0.82,
            "sequencer_random_amount": 0.56,
            "random_recipe": 3,
        },
        "steps": sequence(
            step(0, 0, 0.82, 0.95),
            step(5, 3, 0.58, 0.72, 0.5),
            step(10, 7, 0.74, 0.82, 0.24),
            step(15, 10, 0.5, 0.58, 0.72),
        ),
    },
    {
        "name": "Minimal Click Pluck",
        "category": "Minimal",
        "params": {
            "osc_wave": 3,
            "osc_octave": 1,
            "osc1_level": 0.62,
            "osc2_wave": 0,
            "osc2_octave": 1,
            "osc2_tune": 12.0,
            "osc2_level": 0.24,
            "noise_level": 0.1,
            "amp_attack": 0.001,
            "amp_decay": 0.055,
            "amp_sustain": 0.0,
            "amp_release": 0.09,
            "filter_cutoff": 6200.0,
            "filter_resonance": 0.72,
            "filter_env_amount": 0.5,
            "drive_amount": 0.08,
            "macro_1": 0.5,
            "macro_2": 0.12,
            "macro_4": 0.16,
            "lfo1_sync_rate": 3,
            "lfo1_shape": 4,
            "lfo1_depth": 0.1,
            "mod_env1_decay": 0.06,
            "mod_env1_depth": 0.52,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.2,
            "mod_slot_2_source": 3,
            "mod_slot_2_destination": 2,
            "mod_slot_2_amount": 0.04,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 180.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -4.0,
            "fx_eq_mid_gain": -0.6,
            "fx_eq_high_gain": 1.2,
            "fx_eq_trim": -0.8,
            "fx_comb_enabled": 1,
            "fx_comb_frequency": 540.0,
            "fx_comb_feedback": 0.16,
            "fx_comb_damping": 0.52,
            "fx_comb_mix": 0.08,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 5,
            "fx_delay_time": 0.12,
            "fx_delay_feedback": 0.12,
            "fx_delay_mix": 0.08,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.16,
            "fx_guard_enabled": 1,
            "output_gain": -11.0,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 48,
            "sequencer_gate": 0.16,
            "sequencer_swing": 0.3,
            "sequencer_groove_mode": 1,
            "sequencer_scale": 4,
            "sequencer_accent": 0.42,
            "sequencer_probability": 0.78,
            "sequencer_random_amount": 0.56,
            "random_recipe": 3,
        },
        "steps": sequence(
            step(0, 0, 0.82, 0.9),
            step(5, 3, 0.58, 0.7, 0.5),
            step(10, 7, 0.74, 0.78, 0.24),
            step(15, 10, 0.5, 0.56, 0.72),
        ),
    },
    {
        "name": "Minimal Sub Pulse",
        "category": "Minimal",
        "params": {
            "osc_wave": 0,
            "osc_octave": -1,
            "osc1_level": 0.74,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": 0.04,
            "osc2_level": 0.16,
            "sub_level": 0.7,
            "amp_attack": 0.004,
            "amp_decay": 0.18,
            "amp_sustain": 0.24,
            "amp_release": 0.08,
            "filter_cutoff": 620.0,
            "filter_resonance": 0.38,
            "filter_env_amount": 0.24,
            "drive_amount": 0.16,
            "mono_mode": 1,
            "glide_time": 0.025,
            "macro_3": 0.16,
            "lfo1_sync_rate": 3,
            "lfo1_shape": 4,
            "lfo1_depth": 0.08,
            "mod_env1_decay": 0.12,
            "mod_env1_depth": 0.34,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.1,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 34.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 1.0,
            "fx_eq_mid_gain": -1.8,
            "fx_eq_high_gain": -0.6,
            "fx_eq_trim": -0.8,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.16,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.0,
            "fx_width_mono_cutoff": 150.0,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.04,
            "fx_guard_ceiling": 0.91,
            "output_gain": -10.5,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 36,
            "sequencer_gate": 0.24,
            "sequencer_swing": 0.12,
            "sequencer_groove_mode": 3,
            "sequencer_scale": 4,
            "sequencer_accent": 0.68,
            "sequencer_octave": -1,
            "sequencer_probability": 0.92,
            "sequencer_random_amount": 0.32,
            "random_recipe": 3,
        },
        "steps": sequence(
            step(0, 0, 0.92, 1.0),
            step(4, 0, 0.82, 1.0),
            step(8, 0, 0.86, 1.0),
            step(12, 0, 0.82, 1.0),
            step(14, 3, 0.46, 0.54, 0.1),
        ),
    },
    {
        "name": "Techno Pulse Bass",
        "category": "Techno",
        "params": {
            "osc_wave": 1,
            "osc_octave": -1,
            "osc1_level": 0.84,
            "osc2_wave": 1,
            "osc2_octave": -1,
            "osc2_tune": -0.07,
            "osc2_level": 0.3,
            "sub_level": 0.52,
            "amp_attack": 0.003,
            "amp_decay": 0.2,
            "amp_sustain": 0.22,
            "amp_release": 0.07,
            "filter_cutoff": 900.0,
            "filter_resonance": 0.5,
            "filter_env_amount": 0.34,
            "drive_amount": 0.4,
            "mono_mode": 1,
            "glide_time": 0.025,
            "macro_2": 0.32,
            "macro_3": 0.22,
            "lfo1_sync_rate": 3,
            "lfo1_shape": 4,
            "lfo1_depth": 0.16,
            "mod_env1_decay": 0.16,
            "mod_env1_depth": 0.42,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.14,
            "mod_slot_2_source": 1,
            "mod_slot_2_destination": 4,
            "mod_slot_2_amount": 0.07,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 38.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": 0.9,
            "fx_eq_mid_gain": -0.6,
            "fx_eq_high_gain": 0.2,
            "fx_eq_trim": -0.8,
            "fx_distortion_enabled": 1,
            "fx_distortion_amount": 0.34,
            "fx_bitcrush_enabled": 1,
            "fx_bitcrush_bits": 10.5,
            "fx_bitcrush_downsample": 2.6,
            "fx_bitcrush_mix": 0.12,
            "fx_pump_enabled": 1,
            "fx_pump_rate": 1,
            "fx_pump_depth": 0.22,
            "fx_phaser_enabled": 1,
            "fx_phaser_rate": 0.18,
            "fx_phaser_depth": 0.36,
            "fx_phaser_mix": 0.1,
            "fx_guard_enabled": 1,
            "fx_guard_push": 0.11,
            "fx_guard_ceiling": 0.89,
            "output_gain": -10.8,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 36,
            "sequencer_gate": 0.38,
            "sequencer_swing": 0.08,
            "sequencer_groove_mode": 3,
            "sequencer_scale": 4,
            "sequencer_accent": 0.72,
            "sequencer_octave": -1,
            "sequencer_probability": 0.96,
            "sequencer_random_amount": 0.28,
            "random_recipe": 1,
        },
        "steps": sequence(
            step(0, 0, 0.94, 1.0),
            step(2, 0, 0.52, 0.72, 0.08),
            step(4, 0, 0.86, 1.0),
            step(6, 7, 0.5, 0.68, 0.08),
            step(8, 0, 0.9, 1.0),
            step(10, -5, 0.54, 0.74, 0.08),
            step(12, 0, 0.88, 1.0),
            step(14, 3, 0.5, 0.68, 0.08),
        ),
    },
    {
        "name": "Techno Warehouse Stab",
        "category": "Techno",
        "params": {
            "osc_wave": 2,
            "osc_octave": 0,
            "osc1_level": 0.78,
            "osc2_wave": 1,
            "osc2_octave": 0,
            "osc2_tune": 7.0,
            "osc2_level": 0.5,
            "noise_level": 0.04,
            "amp_attack": 0.003,
            "amp_decay": 0.18,
            "amp_sustain": 0.08,
            "amp_release": 0.24,
            "filter_cutoff": 2200.0,
            "filter_resonance": 0.54,
            "filter_env_amount": 0.32,
            "drive_amount": 0.3,
            "unison_voices": 2,
            "unison_detune": 0.055,
            "unison_spread": 0.32,
            "macro_1": 0.28,
            "macro_2": 0.34,
            "macro_4": 0.2,
            "lfo1_depth": 0.12,
            "mod_env1_decay": 0.16,
            "mod_env1_depth": 0.42,
            "mod_slot_1_source": 2,
            "mod_slot_1_destination": 1,
            "mod_slot_1_amount": 0.16,
            "mod_slot_2_source": 1,
            "mod_slot_2_destination": 5,
            "mod_slot_2_amount": -0.025,
            "mod_slot_3_source": 14,
            "mod_slot_3_destination": 11,
            "mod_slot_3_amount": 0.035,
            "fx_tone_enabled": 1,
            "fx_tone_low_cut": 120.0,
            "fx_eq_enabled": 1,
            "fx_eq_low_gain": -3.2,
            "fx_eq_mid_gain": 0.6,
            "fx_eq_high_gain": 0.8,
            "fx_eq_trim": -0.8,
            "fx_distortion_enabled": 1,
            "fx_distortion_amount": 0.28,
            "fx_phaser_enabled": 1,
            "fx_phaser_rate": 0.22,
            "fx_phaser_depth": 0.44,
            "fx_phaser_mix": 0.16,
            "fx_delay_enabled": 1,
            "fx_delay_rate": 1,
            "fx_delay_time": 0.2,
            "fx_delay_feedback": 0.24,
            "fx_delay_mix": 0.12,
            "fx_reverb_enabled": 1,
            "fx_reverb_size": 0.42,
            "fx_reverb_mix": 0.16,
            "fx_width_enabled": 1,
            "fx_width_amount": 1.24,
            "fx_guard_enabled": 1,
            "fx_guard_ceiling": 0.91,
            "output_gain": -10.0,
            "sequencer_enabled": 1,
            "sequencer_rate": 1,
            "sequencer_root": 48,
            "sequencer_gate": 0.3,
            "sequencer_swing": 0.1,
            "sequencer_groove_mode": 3,
            "sequencer_scale": 2,
            "sequencer_chord_mode": 1,
            "sequencer_chord_voicing": 3,
            "sequencer_chord_strum": 0.08,
            "sequencer_accent": 0.58,
            "sequencer_probability": 0.86,
            "sequencer_random_amount": 0.4,
            "random_recipe": 4,
        },
        "steps": sequence(
            step(3, 0, 0.78, 0.88, 0.18),
            step(7, 7, 0.82, 0.76, 0.24),
            step(11, -5, 0.74, 0.72, 0.2),
            step(15, 10, 0.86, 0.82, 0.28),
        ),
    },
]


def value_string(value):
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def clamp(value, minimum, maximum):
    return max(minimum, min(maximum, value))


def derive_performance_macros(params, explicit_params):
    derived = dict(params)

    if "macro_5" not in explicit_params:
        derived["macro_5"] = clamp((params.get("sub_level", 0.0) * 0.45) + (0.12 if params.get("mono_mode", 0) else 0.0), 0.0, 0.8)

    if "macro_6" not in explicit_params:
        derived["macro_6"] = clamp(params.get("fx_pump_depth", 0.0) + 0.08 if params.get("fx_pump_enabled", 0) else 0.0, 0.0, 0.7)

    if "macro_7" not in explicit_params:
        derived["macro_7"] = clamp((abs(params.get("osc2_tune", 0.0)) / 12.0)
                                   + (params.get("macro_3", 0.0) * 0.4)
                                   + (params.get("unison_detune", 0.0) * 1.8), 0.0, 0.7)

    if "macro_8" not in explicit_params:
        derived["macro_8"] = clamp(params.get("macro_4", 0.0) * 0.82, 0.0, 0.75)

    return derived


def write_preset(preset):
    params = DEFAULTS | preset["params"]
    metadata = FACTORY_METADATA.get(preset["name"], {})
    if "filter_character" not in preset["params"]:
        params["filter_character"] = FILTER_CHARACTER_BY_PRESET.get(preset["name"], 0)
    if "filter_slope" not in preset["params"]:
        params["filter_slope"] = FILTER_SLOPE_BY_PRESET.get(preset["name"], 0)
    if "osc_warp" not in preset["params"]:
        params["osc_warp"] = OSC_WARP_BY_PRESET.get(preset["name"], 0.0)
    if params.get("fx_pump_enabled", 0) and "fx_pump_curve" not in preset["params"]:
        category = preset.get("category", "UKG")
        params["fx_pump_curve"] = {
            "UKG": 2,
            "Minimal": 4,
            "Tech House": 1,
            "Techno": 1,
            "House": 0,
        }.get(category, 0)
    if params.get("fx_delay_enabled", 0) and "fx_delay_sync" not in preset["params"]:
        params["fx_delay_sync"] = 1
        params["fx_delay_rate"] = preset["params"].get("fx_delay_rate", 1)
    params = derive_performance_macros(params, preset["params"])
    root = ElementTree.Element(
        "PARAMETERS",
        {
            "nate_vst_state_version": "1",
            "sample_file": "",
            "preset_name": preset["name"],
            "preset_category": preset.get("category", "UKG"),
            "preset_author": "Nate",
            "preset_source": "Factory",
            "preset_pack": preset.get("pack", metadata.get("pack", "Factory Pack")),
            "preset_key": preset.get("key", metadata.get("key", "Any Key")),
            "preset_bpm": str(preset.get("bpm", metadata.get("bpm", 0))),
            "preset_tags": preset.get("tags", preset_tags(preset, params)),
            **preset["steps"],
        },
    )

    for param_id, value in params.items():
        ElementTree.SubElement(root, "PARAM", {"id": param_id, "value": value_string(value)})

    tree = ElementTree.ElementTree(root)
    ElementTree.indent(tree, space="  ")
    destination = OUTPUT_DIR / f"{preset['name']}.natevstpreset"
    tree.write(destination, encoding="utf-8", xml_declaration=True)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for preset in PRESETS:
        write_preset(preset)


if __name__ == "__main__":
    main()
